include:
  - proxy.yaml

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    env_file:
      - .env

  db:
    image: mysql:8.0
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10
    env_file:
      - .env
